config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders
  resources :members
  resources :users
  resources :items

  root 'orders#index'
  get 'renew/:id' => 'orders#renew'
  get 'return/:id' => 'orders#disable'
  get 'past_orders' => 'orders#old'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :orders
  has_many :members, through: :orders

  validates :name, presence: true
  validates :category, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  has_many :orders
  has_many :items, through: :orders

  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item
  belongs_to :member

  validates :quantity, presence: true
  validates :expire_at, presence: true
  validates :item_id, presence: true
  validates :member_id, presence: true

  def self.active?
    Order.where(status: true)
  end

  def self.inactive?
    Order.where(status: false)
  end

  def self.expired?
    Order.where("expire_at < ?", Date.today).where(status: true)
  end

  def self.renew id
    @order = Order.where(id: id)
    @order.update(expire_at: 7.days.from_now)
  end

  def self.disable id
    @order = Order.where(id: id)
    @order.update(status: false)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    params[:item][:remaining_quantity] = params[:item][:quantity]
    @item = Item.new(item_params)
    if @item.save
      redirect_to :root, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to :root, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end

  private
  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :category, :quantity, :description, :remaining_quantity)
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  def index
    @members = Member.all
  end

  def new
    @member = Member.new
  end

  def edit
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      redirect_to :root, notice: 'Member was successfully created.'
    else
      render :new
    end
  end

  def update
    if @member.update(member_params)
      redirect_to :root, notice: 'Member was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @member.orders.where(status: true).count == 0
      @member.destroy
      redirect_to :root, notice: 'Member was successfully destroyed.'
    else
      flash[:alert] = 'Members with active orders can not be deleted. Mark his/hers open orders as returned and try again.'
      redirect_to root_url
    end
  end

  private
    def set_member
      @member = Member.find(params[:id])
    end

    def member_params
      params.require(:member).permit(:name, :email, :phone)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
    @members = Member.all
    @items = Item.all
    @active = Order.active?
    @expired = Order.expired?
  end

  def old
    @inactive = Order.inactive?
  end

  def renew
    @current_user = current_user
    @order = Order.find_by_id(params[:id])
    Order.renew(params[:id])
    redirect_to :root
    flash[:notice] = "Renewed for 7 days from now. Enjoy!"

    begin
      OrderMailer.delay.renew_order(@order, @current_user).deliver
    rescue Exception => e
    end
  end

  def disable
    borrowed_qty = Order.find_by_id(params[:id]).quantity.to_i
    @borrowed_item = Order.find_by_id(params[:id]).item
    @borrowed_item.increment!(:remaining_quantity, borrowed_qty)
    @current_user = current_user
    @order = Order.find_by_id(params[:id])
    Order.disable(params[:id])
    redirect_to :root
    flash[:notice] = "Item marked as returned. Thank you!"

    begin
      OrderMailer.delay.return_order(@order, @current_user).deliver
    rescue Exception => e
    end
  end

  def new
    @order = Order.new
    @member = Member.all
  end

  def create
    if Item.find_by_id(params[:order][:item_id]).remaining_quantity >= params[:order][:quantity].to_i
      params[:order][:status] = true
      @order = Order.new(order_params)
      if @order.save
        @current_user = current_user
        @borrowed_item = Item.find_by_id(params[:order][:item_id])
        @borrowed_item.decrement!(:remaining_quantity, params[:order][:quantity].to_i)
        redirect_to :root, notice: 'Order was successfully created.'
        begin
          OrderMailer.delay.create_order(@order, @current_user).deliver
        rescue Exception => e
        end
      else
        render :new
      end
    else
      flash[:alert] = 'The quantity you entered is not currently available'
      redirect_to :back
    end
  end

  def destroy
    borrowed_qty = @order.quantity.to_i
    @borrowed_item = @order.item
    @borrowed_item.increment!(:remaining_quantity, borrowed_qty)
    @current_user = current_user
    @order.destroy

    redirect_to orders_url, notice: 'Order was successfully destroyed.'
    begin
      OrderMailer.delay.cancel_order(@order, @current_user).deliver
    rescue Exception => e
    end
  end

  private
    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:quantity, :expire_at, :status, :item_id, :member_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if params[:user][:password].blank? && params[:user][:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    if @user.update(user_params)
      redirect_to :root, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    def set_user
      @user = User.find_by_id(current_user)
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/edit.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Edit Item
        </h1>
        <ol class="breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
          </li>
          <li class="active">Edit Item</li>
        </ol>
      </section>

      <!-- Main content -->
      <section class="content">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-header">
              <div class="box-header with-border">
                <h3 class="box-title">Basic Information</h3>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
              <%= form_for @item do |f| %>
              <% if @item.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@item.errors.count, "error") %>
                  prohibited this item from being saved:</h2>
                <ul>
                  <% @item.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
              <% end %>
              <div class="box-body">
                <div class="form-group">
                  <label>Name</label>
                  <%= f.text_field :name, class: "form-control", placeholder: "Enter Full Name", required: true %>
                </div>
                <div class="form-group">
                  <label>Description</label>
                  <%= f.text_area :description, class: "form-control", rows: "3", laceholder: "Enter Description"%>
                </div>
                <div class="form-group">
                  <label>Quantity</label>
                  <%= f.number_field :quantity, class: "form-control", placeholder: "Enter Quantity", required: true  %>
                </div>
                <div class="form-group">
                  <label>Remaining Quantity</label>
                  <%= f.number_field :remaining_quantity, class: "form-control", placeholder: "Enter Quantity", required: true  %>
                </div>
                <div class="form-group">
                  <label>Category</label>
                  <%= f.select(:category, [["Books","Books"], ["Magazines","Magazines"], ["Electronics","Electronics"], ["Hardware","Hardware"], ["Tools","Tools"]], {}, { :class => 'form-control' })%>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <%= f.submit "Submit", class: "btn btn-primary"%>
              </div>
              <% end %>

            </div>
            <!-- /.box -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
      <div class="pull-right hidden-xs">
        <b>Version</b>
        0.1
      </div>
      Content available under
      <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0</a>.
    </footer>
    <!-- ./wrapper -->
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
  </body>

app/views/items/index.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <div class="content-wrapper">

      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Inventory
          <small>Items</small>
        </h1>
        <ol class="breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
          </li>
          <li class="active">Check Inventory</li>
        </ol>
      </section>

      <section class="content">
        <div class="row">
          <div class="col-xs-12">
            <!-- Main data table -->
            <div class="box">

              <!-- /.box-header -->
              <div class="box-body">
                <table id="example1" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Category</th>
                      <th>Name</th>
                      <th>Description</th>
                      <th>Quantity</th>
                      <th>Available Qty</th>
                      <th>Edit</th>
                      <th>Delete</th>
                      <th>Borrow</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @items.each do |item| %>
                    <tr>
                      <td><%= item.id %></td>
                      <td><%= item.category %></td>
                      <td><%= item.name %></td>
                      <td><%= item.description %></td>
                      <td><%= item.quantity %></td>
                      <td><%= item.remaining_quantity %></td>
                      <td><%= link_to 'Edit', edit_item_path(item) %></td>
                      <td><%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure you want to delete this item?' } %></td>
                      <td><%= link_to 'Borrow', new_order_path(item: item.id) %></td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <!-- /.box-body -->
            </div>
          </div>
        </div>
      </section>
    </div>
    <%= render 'layouts/footer' %>
  </div>
  <script>
    $(function () {
      $("#example1").DataTable();
      $('#example2').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false
      });
    });
  </script>
</body>

app/views/items/new.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">
    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Add Item
        </h1>
        <ol class="breadcrumb">
          <li>
            <a href="#">
              <i class="fa fa-home"></i>
              Home Page</a>
          </li>
          <li class="active">Add Item</li>
        </ol>
      </section>

      <!-- Main content -->
      <section class="content">
        <div class="row">
          <!-- left column -->
          <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-header">
              <div class="box-header with-border">
                <h3 class="box-title">Informations de base</h3>
              </div>
              <!-- /.box-header -->
              <!-- form start -->
              <%= form_for @item do |f| %>
              <% if @item.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@item.errors.count, "error") %>
               interdit la sauvegarde de cet objet:</h2>
                <ul>
                  <% @item.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
              <% end %>
              <div class="box-body">
                <div class="form-group">
                  <label>Nom</label>
                  <%= f.text_field :name, class: "form-control", placeholder: "Entrer Nom", required: true  %>
                </div>
                <div class="form-group">
                  <label>Description</label>
                  <%= f.text_area :description, class: "form-control", rows: "3", laceholder: "Entrer Description"%>
                </div>
                <div class="form-group">
                  <label>Quantité</label>
                  <%= f.number_field :quantity, class: "form-control", placeholder: "Entrer Quantité", required: true  %>
                </div>
                <div class="form-group">
                  <label>Catégory</label>
                  <%= f.select(:category, [["Books","Books"], ["Magazines","Magazines"], ["Electronics","Electronics"], ["Hardware","Hardware"], ["Tools","Tools"]], {}, { :class => 'form-control' })%>
                </div>
              </div>
              <!-- /.box-body -->
              <div class="box-footer">
                <%= f.submit "Enregistrer", class: "btn btn-primary"%>
              </div>
              <% end %>
            </div>
            <!-- /.box -->
          </div>
          <!--/.col (right) -->
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
      <div class="pull-right hidden-xs">
        <b>Version</b>
        0.1
      </div>
      Content available under
      <a href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0</a>.
    </footer>
    <!-- ./wrapper -->
    <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
  </body>

app/views/layouts/_footer.html.erb
<footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b>Version</b>
    0.2
  </div>
  compte github
  <a href="http://github.com/tinosam/">gestion de stock ruby on rails</a>.
</footer>

app/views/layouts/_header.html.erb
<header class="main-header">
  <!-- Logo -->
  <a href="<%= root_url %>" class="logo">
    <!-- mini logo for sidebar mini 50x50 pixels -->
    <span class="logo-mini">
      <b>G</b>Stock</span>
    <!-- logo for regular state and mobile devices -->
    <span class="logo-lg">
      <b>Gestion de Stock (G.S)</b>
    </span>
  </a>
  <!-- Header Navbar: style can be found in header.less -->
  <nav class="navbar navbar-static-top">
    <!-- Sidebar toggle button-->
    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
      <span class="sr-only">Basculer la navigation</span>
    </a>
  </nav>
</header>
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <%= image_tag("user2-160x160.jpg", class: "img-circle") %>
      </div>
      <div class="pull-left info">
        <p><%= current_user.name %></p>
        <a href="<%= edit_user_path(current_user.id) %>">
          <i class="fa fa-edit"></i>
         Editer le profil</a>
        <a href="">
          <%= link_to destroy_user_session_path, method: :delete  do %>
          <i class="fa fa-sign-out"></i>Déconnexion
        <% end %>
        </a>
      </div>
    </div>
    <!-- sidebar menu: : style can be found in sidebar.less -->
    <ul class="sidebar-menu">
      <li class="header">Navigation mère</li>
      <li>
        <a href="<%= root_url %>">
          <i class="fa fa-home"></i>
          <span>Page d'accueil</span>
        </a>
      </li>
      <li>
        <a href="<%= items_path %>">
          <i class="fa fa-search"></i>
          <span>Vérifier l'inventaire</span>
        </a>
      </li>
      <li>
        <a href="<%= past_orders_path %>">
          <i class="fa fa-history"></i>
          <span>Commandes passées</span>
        </a>
      </li>
      <li>
        <a href=" <%= new_item_path %>">
          <i class="fa fa-plus"></i>
          <span>Ajouter un item</span>
        </a>
      </li>
      <li>
        <a href="<%= new_member_path %>">
          <i class="fa fa-user-plus"></i>
          <span>Ajouter un membre</span>
        </a>
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>

app/views/layouts/_notifications.html.erb
<% unless flash.empty? %>
<script type="text/javascript">
  $(document).ready(function () {
    toastr.options = {
      "closeButton": false,
      "debug": true,
      "newestOnTop": false,
      "progressBar": false,
      "positionClass": "toast-top-right",
      "preventDuplicates": false,
      "onclick": null,
      "showDuration": "300",
      "hideDuration": "500",
      "timeOut": "1500",
      "extendedTimeOut": "500",
      "showEasing": "swing",
      "hideEasing": "linear",
      "showMethod": "fadeIn",
      "hideMethod": "fadeOut"
    }
    <% flash.each do |f| %>
    <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'success') %>
    toastr['<%= type %>']('<%= f[1] %>');
    <% end %>
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>gestion de stock</title>
    <%= csrf_meta_tags %>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
    <%= stylesheet_link_tag "toastr.css" %>
    <%= stylesheet_link_tag "AdminLTE.min.css" %>
    <%= stylesheet_link_tag "admin-lte-all-skins.min.css" %>
    <%= stylesheet_link_tag "blue.css" %>
    <%= stylesheet_link_tag "dataTables.bootstrap.css" %>
    <%= stylesheet_link_tag "datepicker3.css" %>

    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" %>
    <%= stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css" %>
    <%= javascript_include_tag "https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"%>
    <%= javascript_include_tag "toastr.min.js" %>
    <%= javascript_include_tag "bootstrap3-wysihtml5.all.min.js"%>
    <%= javascript_include_tag "jquery.dataTables.min.js"%>
    <%= javascript_include_tag "dataTables.bootstrap.min.js"%>
    <%= javascript_include_tag "jquery.slimscroll.min.js"%>
    <%= javascript_include_tag "fastclick.js"%>
    <%= javascript_include_tag "admin-lte-app.min.js"%>
    <%= javascript_include_tag "icheck.min.js"%>
    <%= javascript_include_tag "bootstrap-datepicker.js"%>

  </head>
    <%= render 'layouts/notifications' %>
    <%= yield %>
</html>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :expire_at %>
    <%= f.date_select :expire_at %>
  </div>

  <div class="field">
    <%= f.label :status %>
    <%= f.check_box :status %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/index.html.erb
<body class="hold-transition skin-blue sidebar-mini">
  <div class="wrapper">

    <%= render 'layouts/header' %>
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <section class="content-header">
        <h1>
          Dashboard
          <small>Control panel</small>
        </h1>
        <ol class="breadcrumb">
          <li class="active">
            <a href="#">
              <i class="fa fa-home"></i>
              Acceuil</a>
          </li>
        </ol>
      </section>

      <!-- Main content -->
      <section class="content">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-aqua">
              <div class="inner">
                <h3><%=@items.sum(:quantity)%></h3>
                <p>Articles suivis</p>
              </div>
              <div class="icon">
                <i class="ion ion-search"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-green">
              <div class="inner">
                <h3><%=@items.sum(:remaining_quantity)%></h3>
                <p>Articles disponibles</p>
              </div>
              <div class="icon">
                <i class="ion ion-checkmark"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-red">
              <div class="inner">
                <h3><%= (@items.sum(:quantity) - @items.sum(:remaining_quantity)) %></h3>
                <p>Articles non disponibles</p>
              </div>
              <div class="icon">
                <i class="ion ion-alert"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-yellow">
              <div class="inner">
                <h3><%= @expired.count %></h3>
                <p>Commandes expirées</p>
              </div>
              <div class="icon">
                <i class="ion ion-android-time"></i>
              </div>
            </div>
          </div>
          <!-- ./col -->
        </div>
        <!-- /.row -->

        <div class="row">
          <div class="col-md-6">
            <div class="box">
              <div class="box-header with-border">
                <h3 class="box-title">Orders (<%= @active.count %>)</h3>
              </div>
              <!-- /.box-header -->
              <div class="box-body">
                <table class="table table-bordered table-hover">
                  <thead>
                    <tr>
                      <th>Description</th>
                      <th>Qté</th>
                      <th>Retour par</th>
                      <th>Emprunté par</th>
                      <th>
                        <i class="ion ion-log-in"></i>
                      </th>
                      <th>
                        <i class="ion ion-loop"></i>
                      </th>
                      <th>
                        <i class="ion ion-trash-b"></i>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @active.each do |order| %>
                    <tr>
                      <td>
                        <%= order.item.name %>
                      </td>
                      <td><%= order.quantity %></td>
                      <% if order.expire_at.strftime("%y:%m:%d") >= Date.today.strftime("%y:%m:%d") %>
                      <td>
                        <%= order.expire_at %>
                      </td>
                    <% else %>
                      <td style="color:red;">
                        <%= order.expire_at %>
                      </td>
                      <% end %>
                      <td>
                        <%= order.member.name %>
                      </td>
                      <td>
                        <%= link_to "", { :controller => :orders, :action => :disable, :id => order.id }, { class: "ion ion-log-in"} %>
                      </td>
                      <td>
                        <%= link_to "", { :controller => :orders, :action => :renew, :id => order.id }, { class: "ion ion-loop"} %>
                      </td>
                      <td >
                        <%= link_to order, method: :delete, data: { confirm: 'Êtes-vous sûr? Si vous essayez de retourner un article, il est recommandé d utiliser le bouton "retour".' } do %>
                        <i class="ion ion-trash-b"></i>
                        <% end %>
                      </td>
                    </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
            <!-- /.box -->
          </div>
          <!-- ./col -->

          <div class="col-md-6">
            <div class="box">
              <div class="box-header with-border">
                <h3 class="box-title">Members (<%= @members.count %>)</h3>
              </div>
              <!-- /.box-header -->
              <div class="box-body">
                <table class="table table-bordered table-hover">
                  <tr>
                    <th>Nom</th>
                    <th>E-mail</th>
                    <th>Mobile</th>
                    <th>
                      <i class="ion ion-edit"></i>
                    </th>
                    <th>
                      <i class="ion ion-trash-b"></i>
                    </th>
                  </tr>
                  <% @members.each do |member| %>
                  <tr>
                    <td><%= member.name %></td>
                    <td><%= member.email %></td>
                    <td><%= member.phone %></td>
                    <td><%= link_to "", edit_member_path(member), { class: "ion ion-edit"} %></td>
                    <td>
                      <%= link_to member, method: :delete, data: { confirm: 'Êtes-vous sûr?' } do %>
                      <i class="ion ion-trash-b"></i>
                      <% end %>
                    </td>
                  </tr>
                  <% end %>
                </table>
              </div>
            </div>
            <!-- /.box -->
          </div>
          <!-- ./col -->
        </div>
        <!-- /.row -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <%= render 'layouts/footer' %>
    <script>
      $.widget.bridge('uibutton', $.ui.button);
    </script>
    <script>
      $(function () {
        $("#example1").DataTable();
        $('#example2').DataTable({
          "paging": true,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": true,
          "autoWidth": false
        });
      });
    </script>
  </body>